/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'thivyalakshimi' at '7/20/16 2:38 PM' with Gradle 2.14
 *
 * @author thivyalakshimi, @date 7/20/16 2:38 PM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
